mukdaejang/foodking

- public/index.html
- src/components/Portal/index.tsx
- src/components/index.ts
- src/components/search/SearchBox.styled.tsx
- src/components/search/SearchKeyword.tsx
- src/components/search/SearchModal.tsx
- src/components/search/index.tsx
#16 #26 
feat: click SearchBox render keywordSuggestion
- add position : absolute , z-index
- use portal for modal effect
> Banner - Portal로 Modal화

- .gitignore
- src/components/SurroundPopulars/SurroundPopular.styled.tsx
- src/components/SurroundPopulars/SurroundPopular.tsx
- src/components/SurroundPopulars/index.tsx
- src/components/index.ts
- src/components/style/index.tsx
- src/pages/MatjibList/index.tsx
- src/styles/emotion.d.ts
- src/styles/theme.ts
- seperate files in SurroundPopular.tsx and SurroundPopulars/index.tsx
> feat: #33 detail page markup and styling

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
#44 
템플릿을 develop 브랜치에 올려놓아서 이슈와 풀리퀘스트 템플릿이 적용이 되지 않아
메인 브랜치에 파일을 직접 업로드
> #44 conf: add issue, pull_request

- src/Router.tsx
- src/components/RestaurantInfo/RestaurantInfo.styled.tsx
- src/components/RestaurantInfo/index.tsx
- src/components/index.ts
- src/pages/MatjibList/index.tsx
- src/pages/Restaurants/index.tsx
- src/pages/index.ts
- tsconfig.json
#59
- markup
- styling
- 가게정보/리뷰쓰기 재사용하려 했으나 아직 미비로 보류
> feat: DetailPage/RestaurantInfo markup and styling

- src/components/Filter/Local/Local.styled.tsx
- src/components/Filter/Local/index.tsx
- src/components/Portal/index.tsx
- src/components/Search/SearchBox.styled.tsx
- src/components/Search/SearchKeyword.tsx
- src/components/Search/index.tsx
- src/pages/SearchResult/index.tsx
Banner - Tab 포커싱 
#18 
- SearchModal이 tab이 가능하도록 tag들을 button으로 수정
> Banner - Tab 포커싱 

- src/components/Header/index.tsx
- src/components/Modal/SocialLogin.tsx
- src/components/ProfileIcon/index.tsx
- src/firebase/auth.ts
- src/store/auth/auth-actions.ts
- src/store/auth/auth-slice.ts
- src/store/index.ts
- src/store/modal/modal-slice.ts
#85 
login 유무, modal open/close state를  redux로 관리
- login state 관리
- modal state 관리
> Redux로 Login , Modal state 관리하기

- src/components/BestRestaurantItem/bestRestaurantItem.styled.tsx
- src/components/BestRestaurantItem/index.tsx
- src/components/IconButton/iconButton.styled.tsx
- src/components/IconButton/index.tsx
- src/components/index.ts
#36 
- pros으로 두개를 받음
- img는 초기의 이미지
- event는 해당 버튼에 걸 이벤트
> 가고싶다 같은 아이콘 버튼 분리

- src/components/Search/SearchBox.styled.tsx
- src/components/Search/SearchKeyword.tsx
- src/components/Search/SearchModal.tsx
- src/components/Search/index.tsx
#90 
- form 태그 추가 (시멘틱을 위해)
- 추가된 form 태그 때문에 css 업데이트
- Link 태그 제거
> [검색창] Modal의 추천 검색어 클릭시 Link 오류

- src/components/Button/index.tsx
- src/components/ReviewWrite/index.tsx
- src/components/ReviewWrite/reviewWrite.styled.tsx
#84 #95 
- 플러스 박스 클릭시 이미지 파일 선택 / 이미지 파일 선택하면 blob으로 데이터를 가짐(state로 가지고 있음)
- 선택한 이미지는 미리보기 지원
- 마우스 오버시 x버튼이 나오고 클릭시 미리보기에서 지움(state에서도 해당 데이터 지워짐)
> review page add image file form

- src/components/Header/Header.styled.tsx
- src/components/Header/index.tsx
- src/styles/emotion.d.ts
- src/styles/theme.ts
#103 
- 헤더 스크롤 이벤트 추가
- 일정 스크롤 높이(200px)에 따라 헤더 css 변경
- header css styled component 로 변경 (props를 통해 css 변경가능하도록 구현)
> 스크롤길이에 따른 헤더 css 변경

- src/components/Header/Header.styled.tsx
- src/components/Header/index.tsx
- src/components/Reviews/Review.styled.tsx
- src/components/Reviews/Review.tsx
- src/pages/Restaurants/Images.tsx
- src/pages/Restaurants/index.tsx
- seperate exist Image in Review Component
- markup and styling images in detail page
- add blankDiv under header tag
> feat: [Detail / Images] markup and styling 

- src/components/Filter/Local/Local.styled.tsx
- src/components/Filter/Local/index.tsx
- src/components/Search/SearchBox.styled.tsx
- src/components/Search/SearchKeyword.tsx
- src/components/Search/SearchModal.tsx
- src/components/Search/index.tsx
- src/pages/SearchResult/index.tsx
#70 
- CSS를 선택하는 문제를 배열로 관리해, 리스트 렌더링을 방식으로 해결.
- 기존의 Keyword 컴포넌트의 스타일을 따로 분리시킴.
> [검색창] DOM API 제거

- src/components/Carousel/index.tsx
- src/components/Category/index.tsx
- src/components/ProfileIcon/List.tsx
- src/components/ProfileIcon/ProfileIcon.styled.tsx
- src/components/Restaurants/index.tsx
- src/firebase/request.ts
- src/firebase/type.ts
#121 #122
- 프로필 아이콘 창에서 최근 봇 맛집 overflow 시 세로 스크롤 생성
- firebase에서 맛집리스트 가져오는 get api 작성
> 프로필 아이콘 스크롤창 & 개별 삭제 버튼

- src/components/BestRestaurantItem/bestRestaurantItem.styled.tsx
- src/components/BestRestaurantItem/index.tsx
- src/components/BestRestaurants/index.tsx
- src/components/Carousel/carousel.styled.tsx
- src/components/Carousel/index.tsx
- src/components/CategoryItem/category_item.styled.tsx
- src/components/CategoryItem/index.tsx
- src/components/Restaurants/restaurants.styled.tsx
- src/components/style/index.tsx
- src/firebase/request.ts
- src/pages/Main/index.tsx
#143 #130 
- best restaurants 페이지 링크 수정(영어로)
- 폰트 크기 및 중앙 정렬
- DB 데이터 사용 및 형식 맞춰주기
- 이미지 가져오기
> best restaurants page 링크 수정 및 데이터, 이미지 사용

- src/components/Header/index.tsx
- src/pages/Restaurants/index.tsx
- 로고 a 태그 Link 태그로 변경
- 상세페이지에서 modal dispatch 부분 주석처리
> Link 태그로 변경 & modal dispatch 주석처리

- src/components/ProfileIcon/List.tsx
- src/components/ProfileIcon/index.tsx
- src/firebase/request.ts
- src/firebase/type.ts
> refactor : #152 refactoring interface

- src/components/ProfileIcon/List.tsx
- src/components/ProfileIcon/index.tsx
- src/firebase/request.ts
- src/firebase/type.ts
#155 
- 프로필 아이콘 클릭 시 위치 내려가는 버그 해결
- 최근 본 / 가고싶다 에서 li 클릭 시 overlay Modal off 안되는 버그 해결
> 프로필 아이콘 버그 수정

- src/components/Search/SearchKeyword.tsx
- src/components/Search/SearchModal.tsx
- src/components/Search/index.tsx
- src/firebase/api/searchkeyword.ts
- src/firebase/type.ts
- src/pages/Main/index.tsx
- src/store/searchkeyword/keyword-slice.ts
#160 
- firebase의 데이터를 검색창 모달에서 렌더링한다.
- 메인페이지가 렌더링될 때, redux store에 저장해놓는다. 
- 각각의 컴포넌트에서 해당 데이터를 불러서 사용, 수정한다.
- 최근 검색어를 localStorage에 저장해 기록해놓는다.
> [메인페이지 / 검색창 기능] firebase 데이터로 검색어 추천 렌더링

- src/firebase/request.ts
#162
- remove blob request in getImageDocs function / requests.ts
> refac: modify image download data

- src/components/RestaurantInfo/index.tsx
#164 
- 상세페이지에서 리뷰작성, 즐겨찾기 기능 추가 
- 비로그인 상태에서 소셜로그인 모달창 보여주기
> 상세페이지 리뷰작성 & 즐겨찾기 기능 (로그인 유무에 따라)

- package.json
- src/components/ProfileIcon/List.tsx
- src/components/ProfileIcon/ProfileIcon.styled.tsx
- src/components/ProfileIcon/index.tsx
- src/index.tsx
- src/store/index.ts
#154 
- 최근 본 맛집, 가고싶다 이미지 렌더링
- 로드중일때는 skeleton으로 회색 처리로 사용자에게 보여주기
> 프로필 아이콘 li 이미지 렌더링 

- src/components/Filter/Local/index.tsx
- src/components/Filter/index.tsx
- src/components/ProfileIcon/List.tsx
- src/components/ProfileIcon/index.tsx
- src/components/Search/SearchKeyword.tsx
- src/firebase/api/searchkeyword.ts
- src/firebase/type.ts
- src/pages/SearchResult/index.tsx
- src/pages/SearchResult/searchResult.styled.tsx
#133 
#134 
- fetch된 검색결과 데이터를 검색결과 페이지에 렌더링
- filter 컴포넌트의 적용하기 버튼을 누르면 해당된 음식점을 필터링해서 보여준다.
- '서울' 키워드를 입력했으면 주소에 '서울' 키워드가 들어간 모든 음식점을 검사한다.
- '서울맛집' 키워드는 '서울맛집' 키워드를 꼭 포함해야 한다. '서울특별시' 키워드는 검색하지 않는다.
- 반면에 음식점 이름에 '서울맛집 삼겹살' 이라면 '서울맛집' 키워드를 포함하므로 검색한다.
> [검색결과페이지 / 필터] 필터에서 선택한 조건대로 필터링 처리

- src/components/Banner/Banner.styled.tsx
- src/components/Banner/index.tsx
- src/components/Header/Header.styled.tsx
- src/components/Header/index.tsx
- src/components/Search/SearchBox.styled.tsx
#178 
- 헤더 컴포넌트의 css 분리
- 메인페이지일 경우에만 SearchBox 렌더링 되도록 설정
- z-index 관련 문제가 발생
> [헤더] 헤더 컴포넌트의 input 검색창 컴포넌트로 대체

- public/index.html
- src/components/Header/index.tsx
- src/components/Modal/Modal.styled.tsx
- src/components/Portal/index.tsx
- src/components/ProfileIcon/ProfileIcon.styled.tsx
- src/components/Search/SearchBox.styled.tsx
- src/components/index.ts
when clicked Profile Icon, SearchBox is also activated.
so make new div Banner background Portal.
#178 
- 같은 Portal을 공유하고 있어 프로필 아이콘을 클릭했을 때, 검색창이 보이는 z-index 문제가 있었다.
- 새로운 Banner-background 포탈을 만들어줬다. 검색창이 열릴 때, Banner-background가 열리도록 설정.
> feat: make banner-background div tag for Modal

- src/components/Header/Header.styled.tsx
- src/components/Search/SearchKeyword.tsx
- src/pages/SearchResult/index.tsx
- src/pages/SearchResult/searchResult.styled.tsx
#186 
- Header 컴포넌트에서 z-index 문제 해결
- Header에서 키워드 검색 시, scroll to top을 적용.
- 검색결과페이지에서 검색된 데이터가 없을 때, NoDisplay를 렌더링 해준다.
- 비동기 작업이 끝나기 전에 NoDisplay가 렌더링 되는 문제가 있음.
> [검색창] Header 컴포넌트에서 z-index 문제

- src/components/BestRestaurantItem/index.tsx
- src/components/CategoryItem/index.tsx
- src/components/Header/Header.styled.tsx
- src/components/Map/index.tsx
- src/components/Modal/SocialLogin.tsx
- src/components/ProfileIcon/index.tsx
- src/components/RestaurantItem/index.tsx
- src/components/Search/SearchBox.styled.tsx
- src/components/Search/index.tsx
> 페이지 이동 시 스크롤 위치 초기화

- src/components/RestaurantInfo/RestaurantInfo.styled.tsx
- src/components/RestaurantInfo/index.tsx
- src/firebase/request.ts
- src/firebase/type.ts
- src/pages/Restaurants/index.tsx
#196 
- 상세페이지 들어갈 때 마다 조회수 1 증가
- 상세페이지 렌더링
> feat : #196 add post views update api & rendering postInfo

- src/components/ProfileIcon/List.tsx
- src/components/ProfileIcon/index.tsx
#199 
- localStorage에서 favorite 배열의 postId 삭제 안되는 버그 해결
> fix : resolve rendering img bug

- src/Router.tsx
- src/components/ReviewWrite/index.tsx
- src/components/Reviews/Review.styled.tsx
- src/components/Reviews/Review.tsx
- src/components/Reviews/index.tsx
- src/firebase/request.ts
- src/firebase/type.ts
- src/pages/Restaurants/Images.tsx
- src/store/restaurants/restaurants-actions.ts
- src/store/restaurants/restaurants-slice.ts
Reverts mukdaejang/foodking#202
> Revert "리뷰 수정 기능"

- src/Router.tsx
- src/components/ReviewWrite/index.tsx
- src/components/Reviews/Review.styled.tsx
- src/components/Reviews/Review.tsx
- src/components/Reviews/index.tsx
- src/firebase/request.ts
- src/firebase/type.ts
- src/pages/Restaurants/Images.tsx
- src/store/restaurants/restaurants-actions.ts
- src/store/restaurants/restaurants-slice.ts
Reverts mukdaejang/foodking#203
> Revert "Revert "리뷰 수정 기능""

- src/components/Reviews/Review.tsx
- src/components/Reviews/index.tsx
- src/firebase/request.ts
- src/firebase/type.ts
#166 
- fetch user data by review id
> feat: render user profile image and name

- src/components/Carousel/index.tsx
- src/components/Category/category.styled.tsx
- src/components/Category/index.tsx
- src/components/CategoryItem/index.tsx
- src/components/RestaurantItem/index.tsx
- src/components/Restaurants/index.tsx
- 캐러셀 컨트롤 버튼 중앙으로 수정
- 스켈레톤 ui 개선
> 스켈레톤 ui 로드 수정

- README.md
- src/components/Modal/Modal.styled.tsx
hotfix
- fix opacity in Login Modal
> hotfix: fix opacity
